#ifndef PORTAFOLIO_CPP_N4_18_ARCHIVOS_TEXTO_ESCRITURA_HPP
#define PORTAFOLIO_CPP_N4_18_ARCHIVOS_TEXTO_ESCRITURA_HPP

// Enunciado: Guardar datos de usuarios en un archivo.
// Autor: Marvin Cifuentes

#endif // PORTAFOLIO_CPP_N4_18_ARCHIVOS_TEXTO_ESCRITURA_HPP
